config/routes.rb
Rails.application.routes.draw do

  namespace :api, defaults: { format: :json } do
    resource :current_user, controller: 'current_user', only: [:show]
    resources :posts, only: [:index, :show, :create, :update] do
      resource :state, only: [:update], controller: 'posts/state'
    end
    resources :tree_posts, only: [:index]
    resources :templates, only: [:index]
    resources :playlist_items
  end

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout
  get 'logout' => 'user_sessions#destroy'

  namespace :admin do
    get '/' => 'dashboard#index'
    resources :users, only:[:index, :show, :new, :create, :edit, :update]
  end

  get "/(*all)", to: "front#index"
  root "front#index"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  email            :string(255)      not null
#  host             :boolean          default("0"), not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  crypted_password :string(255)
#  salt             :string(255)
#  admin            :boolean          default("0"), not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :posts
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes["password"] }
  validates :password, confirmation: true, if: -> { new_record? || changes["password"] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes["password"] }

  validates :email, uniqueness: true

  validates :name, uniqueness: true, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(new_user_params)
    if @user.save
      redirect_to admin_users_url, notice: "user created"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(update_user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  private

  def new_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def update_user_params
    params.require(:user).permit(:name, :email, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/admin/users/_form.html.slim
= bootstrap_form_for [:admin, user] do |f|
  = f.text_field :name
  = f.text_field :email
  = f.password_field :password
  = f.password_field :password_confirmation
  = f.check_box :admin
  = f.submit "submit"

app/views/admin/users/edit.html.slim
h2 #{@user.name} 編集
== render 'form', user: @user

app/views/admin/users/index.html.slim
h2 ユーザー管理
= link_to '新規ユーザー', new_admin_user_path, class: 'btn btn-primary'

table.table
  tr
    th Name
    th Role

  - @users.each do |user|
    tr
      td
        = user.name
      td
        = user.admin? ? '管理者' : '一般'
      td
       = link_to 'Edit',  edit_admin_user_path(user), class: 'btn btn-info'

app/views/admin/users/new.html.slim
h2 新規ユーザー登録
= render 'form', user: @user